INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES('Tomate', 2)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Carbonara', 1.5)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Barbacoa', 1)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Mozzarela', 2.5)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Cheddar', 1.7)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Suizo', 2)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Provolone', 2.3)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Ternera', 4)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Pollo', 3.6)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Cerdo', 4.3)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Atun', 3)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Pepperoni', 2.3)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Champiñon', 1.6)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Cebolla', 2.1)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Aceitunas', 2.5)
INSERT INTO Ingredientes (Nombre_ingrediente, Precio_ingrediente) VALUES ('Pimieneto', 1.1)

